apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: antlion-clojure
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: antlion-clojure
    spec:
      containers:
      - name: antlion-clojure
        image: asia.gcr.io/boxp-tk/antlion-clojure:${CIRCLE_SHA1}
        env:
          - name: ANTLION_CLOJURE_TOKEN
            valueFrom:
              secretKeyRef:
                name: antlion-clojure
                key: token
          - name: ANTLION_CLOJURE_INVITE_TOKEN
            valueFrom:
              secretKeyRef:
                name: antlion-clojure
                key: invite-token
          - name: ANTLION_CLOJURE_MASTER_USER_NAME
            valueFrom:
              secretKeyRef:
                name: antlion-clojure
                key: master-user-name
          - name: ANTLION_CLOJURE_GITHUB_OAUTH_TOKEN
            valueFrom:
              secretKeyRef:
                name: antlion-clojure
                key: github-oauth-token
          - name: REDIS_MASTER_HOST
            value: rd-0.redis.default.svc.cluster.local
          - name: REDIS_MASTER_PORT
            value: "6379"
          - name: REDIS_SLAVE_HOST
            value: redis
          - name: REDIS_SLAVE_PORT
            value: "6379"
